name: flutter_notification_manager
description: "Android Notification Manager plugin that allows to create and manage notification channels"
version: 1.0.0
repository: https://github.com/klisiewicz/flutter-notification-manager

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  json_annotation: ^4.8.1
  flutter:
    sdk: flutter
  meta: ^1.10.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.klisiewicz.flutter_notification_manager
        pluginClass: FlutterNotificationManagerPlugin
